### ISSUE TITLE
Bug: the extension is working inconsistently (and other suggestions)

### ISSUE THREAD

**Issue by alexseyk** [blmage/duolingo-solution-viewer#3] opened 2020-05-24 15:47 UTC
FYI : 1) There is no sorting in En -> Es course  with Crome . This happens for sentences with word bank 
<img width="595" alt="Screen Shot 2020-05-24 at 22 23 23" src="https://user-images.githubusercontent.com/60418150/82757855-376ee780-9e0d-11ea-8833-34ebb8da1f2e.png">
2) please add icon, as in mobile (web view) it is not possible to access solutions 
<img width="365" alt="Screen Shot 2020-05-24 at 22 24 42" src="https://user-images.githubusercontent.com/60418150/82757890-7604a200-9e0d-11ea-9d26-36bd6cfddf6f.png">
<img width="550" alt="Screen Shot 2020-05-24 at 22 24 01" src="https://user-images.githubusercontent.com/60418150/82757905-8a489f00-9e0d-11ea-95b9-0ae583e94ae0.png">

3) Make a pop-up wider and / or give an option to open it in a new page
and / or add option to see possible solutions on the corresponding discussion pages in the forum

4) user answer is not shown 

5) Add a hot key to open/ show solution  for example cntrl (or shift)  + S

6) **Extension does not work with practice type exercises** ( timed and not timed )  for Level 5 skills  practice / restore or lower level skills with direct links from Duome or with DuoStength extension. Same for general  practice 
 
7) same for checkpoint skills test out i.e. bigtest

8) Is it possible to sort by most popular solution / translation / answer ?

**Comment by blmage** [comment] 2020-05-25 10:16
Thanks for your feedback and suggestions!
I'll get back to you on every point as soon as I have some time (after the next release).

**Comment by blmage** [comment] 2020-05-28 18:01
Based on the latest version (`1.2.0`):
1. **Fixed**
  Answers entered via the word bank are now correctly detected (previously, similarity scores could not be computed).
1. **Fixed**
  The extension now uses its own icon instead of reusing one which was not always accessible (due to CORS).
1. **Added**
  You can now choose between three pop-up sizes: _default_, _fit-to-content_, and _maximized_.
1. **Fixed**
  See point 1.
1. **Added**
  Use `S` to open the pop-up and `Esc` to close it.
1. **Wontfix**
1. **Wontfix**
  This is a known limitation, unfortunately there is most likely nothing we can do about it (the extension's script always gets added to the page after the challenges have been loaded, so it can't intercept those).
1. **Wontfix**
  This would be a must-have, but there are no such statistics available (also, solutions are in fact stored as graphs with words as vertices, and not as whole sentences).

Thanks again for your detailed feedback!

**Comment by alexseyk** [comment] 2020-06-03 14:18
FYI: related to  6 & 7. Somehow extension works for skills test out (i.e. via a key icon)

**Comment by blmage** [comment] 2020-06-06 15:05
Yes, the extension may sometimes work even when we don't expect it to, because it all depends on the loading order of the page scripts. Unfortunately, we don't have a grip on this, and the extension scripts themselves come quite late in the process, so this is likely bound to remain random.

**Comment by alexseyk** [comment] 2020-06-08 01:42
ok. i see. Sadly sometimes the extension does not work for normal lessons :( i am on spanish from english course now. i.e. when i use start button

**Comment by blmage** [comment] 2020-06-08 18:36
Ok, it should at least work consistently on normal lessons, so this is abnormal. I've tried to launch a few lessons on the English -> Spanish course, but could not reproduce it yet.

I'd be curious to know what's wrong here, but errors are currenty only logged when using the development build. Would you have the possibility to build and test it?
Otherwise, I'll think about adding an option to enable the logging of errors!

**Comment by alexseyk** [comment] 2020-06-09 04:10
Sure, i have time to test but you'll have to give me instructions how to  compile a build. I tried loading your code but got an error 
"Manifest file is missing or unreadable"

**Comment by blmage** [comment] 2020-06-12 10:46
Just so you know, I'll come back to this when I have finished releasing version `2.1.0`.

**Comment by blmage** [comment] 2020-06-14 09:23
Actually, I may have an idea as to how to improve the extension's consistency. I'll try to implement it in version `2.3.0`, we'll check from there if things seem to go better or not.

Reopening the issue to help keep track of this.

**Comment by blmage** [comment] 2020-06-27 09:52
I've just released version 3.0.0, which seems to work much more consistently (even on page reload and direct access). Can you check it and tell if that's also the case for you? (it should be available soon on the Chrome Web Store) Thanks!

**Comment by blmage** [comment] 2020-06-29 13:11
Sorry, did not mean to close this already.

**Comment by alexseyk** [comment] 2020-07-09 04:01
Thanks. It works great, even for practice &  checkpoints bigtest now ! :)  Also it works with https://github.com/derat/duoleavemealone too:) Not sure if it is something you've done or **derat** or due to changes in Duolingo. Anyway thanks! I hope it stays this way.

**Comment by blmage** [comment] 2020-07-09 10:28
That's great news, thanks for the update!

**Closed by blmage** 2020-07-09 10:28 UTC
Labels: bug, enhancement
