### ISSUE TITLE
it stopped working with new UI

### ISSUE THREAD

**Issue by alexseyk** [blmage/duolingo-solution-viewer#189] opened 2022-10-16 14:05 UTC
Hi
it seems that your script no longer works after latest UI redesign :( 
https://blog.duolingo.com/new-duolingo-home-screen-design/

<img width="1301" alt="Screen Shot 2022-10-16 at 20 59 17" src="https://user-images.githubusercontent.com/60418150/196039814-c644ea71-5b3d-479c-91b1-247beb15d6a2.png">

please fix it, thanks !

**Comment by blmage** [comment] 2022-10-16 18:47
Everything works fine on my side on a new account on which the redesign is active. 

This could be related to a v2-specific A/B test named `web_delight_prefetch_v2_sessions`, but I'm not sure that this one can be enabled by playing with the `duo.state` in the local storage.

I'll see what I can do as soon as possible, but if I don't get anywhere, do you have an account on which the problem can be reproduced, that you could share with me? (in which case, feel free to drop an email to the address indicated on my profile)

Thanks!

**Comment by alexseyk** [comment] 2022-10-17 06:07
My apologies for the false alarm.

It started working after i cleared the cache and reinstalled the script

**Comment by blmage** [comment] 2022-10-17 10:23
No worries! I could reproduce the problem by enabling the `web_delight_prefetch_v2_sessions` experiment, so you probably opted out of it by clearing the cache (and in any case, it also was the perfect opportunity to test the extension against the new UI).

I'm reopening the issue, because it might still affect other users.

**Comment by blmage** [comment] 2022-10-17 10:28
Pre-fetched sessions seem to be stored using Indexed DB, under the `prefetchedSessions` store of the `duolingo` database.

Loading all pre-fetched sessions each time the background script starts is certainly a no go.

I still need to figure out then how the app chooses a given session over the others, and whether we can detect when this process occurs.

**Comment by blmage** [comment] 2022-10-19 10:22
Fixed in version **4.11.0**.

Thanks again for your report!

**Closed by blmage** 2022-10-19 10:22 UTC
Labels: bug
